### ISSUE TITLE
Look into cleaning up changes from clinvar, civic, + moa impact analysis

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/variation-normalizer-manuscript#55]
We are just trying to get #35 merged, so I tried not to make comments on things that could wait til later. I think there are some additional places that could be refactored. These notebooks are pretty large, so should look to make sure things are well documented (why things are being done), good naming, and DRY principle to help decrease the number of cells. This is mainly for readability so newcomers can easily understand what is happening in these notebooks.

**Comment by korikuzma** [comment]
@anastasiabratulin are you going to have time to do this?

**Comment by anastasiabratulin** [comment]
@korikuzma I've tried to tidy as much as I can but I can definitely go back. I think it would be more efficient if someone could go through and tell me what is unclear in documentation and what naming needs to be changed since I am not able to be objective

**Comment by anastasiabratulin** [comment]
@korikuzma I see what you mean, I will go back over. 
But specifically in this case, "total" is speaking to the total of variants in this specific analysis not in CIViC. Since a lot of my variable names get added to as the analysis progresses, the names will get very convoluted very quickly if I don't choose simple ones in the beginning.

**Comment by korikuzma** [comment]
> @korikuzma I see what you mean, I will go back over. But specifically in this case, "total" is speaking to the total of variants in this specific analysis not in CIViC. Since a lot of my variable names get added to as the analysis progresses, the names will get very convoluted very quickly if I don't choose simple ones in the beginning.

The total was an example from my refactoring. See #65

**Comment by korikuzma** [comment]
We're not going to prioritize this anymore. So closing
