### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/variation-normalizer-manuscript#63]
Talk more about the files + which order to run in. 

@wesleygoar anything else that you want to be added?

**Comment by wesleygoar** [comment]
@korikuzma good question. Maybe we should put in a statement for about who to contact if they have issues getting the normalizer up and running since that will be the trickiest part for most people.

**Comment by korikuzma** [comment]
@wesleygoar do we have a help email?

**Comment by korikuzma** [comment]
@wesleygoar or i can just say make an issue in a repo

**Comment by wesleygoar** [comment]
@korikuzma lets go with make an issue in the repo for now
