### ISSUE TITLE
Add compute environment

### ISSUE THREAD

**Issue by bwalsh** [GenomicMedLab/variation-normalizer-manuscript#88]
As an informatician, before I get started, it would be useful to know how many cores, diskspace, memory, etc. 
It would also be useful to know what environments it has been tested in linux, aws, macos, etc.

https://github.com/GenomicMedLab/variation-normalizer-manuscript/blob/1fa8cf94a2fc5ea726efd62732efd29e5d8662e7/README.md?plain=1#L8

**Comment by korikuzma** [comment]
This was done in #93
