### ISSUE TITLE
Add Results

### ISSUE THREAD

**Issue by bwalsh** [GenomicMedLab/variation-normalizer-manuscript#89]
It would be useful to have a figure or small screen shot for motivation.   ie.  After I go through all these steps, what will I be able to do/see?

https://github.com/GenomicMedLab/variation-normalizer-manuscript/blob/1fa8cf94a2fc5ea726efd62732efd29e5d8662e7/README.md?plain=1#L149

**Comment by korikuzma** [comment]
@wesleygoar what do you want here?

**Comment by wesleygoar** [comment]
I think maybe the new bar graph figure that Jeremy is creating would be a nice hook. @ahwagner what do you think?

**Comment by korikuzma** [comment]
@jarbesfeld I'm going to re-assign this issue to you. Could you also provide some text on the figure?

**Comment by jarbesfeld** [comment]
@korikuzma I can the bar graph figure + text once we finalize the 1st figure. Should the figure and text go in the README?

**Comment by wesleygoar** [comment]
@jarbesfeld, Yes. This is our hook for them to want to do it.

**Comment by jarbesfeld** [comment]
@wesleygoar @korikuzma Is this what we were thinking of adding to the README (https://github.com/GenomicMedLab/variation-normalizer-manuscript/blob/patient-graph/README.md#results)? I can change the plot and create a PR once we finalize the figure.

**Comment by wesleygoar** [comment]
@jarbesfeld yes

**Comment by korikuzma** [comment]
This was done in #101
